name: RDP

on:
  workflow_dispatch:
    inputs:
      ngrok_region:
        description: 'Region'
        required: false
        default: 'ap'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 1450

    steps:
      - name: R
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok
          .\ngrok\ngrok.exe authtoken 3CALF22QQXcRRx5hlCGVyW04O5S_2VerPxZYcFEnDCuiJjgwV
          
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          New-LocalUser "DucthengTechDz" -Password (ConvertTo-SecureString "W1nd0ws-P4ssw0rd-2025!" -AsPlainText -Force)
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "DucthengTechDz"
          Add-LocalGroupMember -Group "Administrators" -Member "DucthengTechDz"
          
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "fEnableVirtualizedGraphics" -Value 1 -Type DWord -Force
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "AVCHardwareEncodePreferred" -Value 1 -Type DWord -Force
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "MinFrameRate" -Value 120 -Type DWord -Force
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "fDisableWallpaper" -Value 1 -Type DWord -Force
          powercfg /setactive a1841308-3541-4fab-bc81-f71556f20b4a
          
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389 --region=${{ github.event.inputs.ngrok_region }}" -NoNewWindow
          Start-Sleep -Seconds 5
          
          $response = Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels" -UseBasicParsing
          $tunnelUrl = ($response.Content | ConvertFrom-Json).tunnels[0].public_url -replace 'tcp://', ''
          
          # IN RA FORMAT ĐẶC BIỆT ĐỂ GITHUB HIỂN THỊ
          echo "::notice::NGROK_URL=$tunnelUrl"
          echo "::notice::RDP_USER=DucthengTechDz"
          echo "::notice::RDP_PASS=W1nd0ws-P4ssw0rd-2025!"
          
          # HOẶC IN RA STEP SUMMARY
          echo "NGROK_URL=$tunnelUrl" >> $env:GITHUB_STEP_SUMMARY
          echo "RDP_USER=DucthengTechDz" >> $env:GITHUB_STEP_SUMMARY
          echo "RDP_PASS=W1nd0ws-P4ssw0rd-2025!" >> $env:GITHUB_STEP_SUMMARY
          
          Start-Sleep -Seconds 86400
